USE [master]
GO
/****** 物件:  Database [FruitBarDB]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
CREATE DATABASE [FruitBarDB]
GO
ALTER DATABASE [FruitBarDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FruitBarDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FruitBarDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FruitBarDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FruitBarDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FruitBarDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FruitBarDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FruitBarDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FruitBarDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FruitBarDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FruitBarDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FruitBarDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FruitBarDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FruitBarDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FruitBarDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FruitBarDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FruitBarDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FruitBarDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FruitBarDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FruitBarDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FruitBarDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FruitBarDB] SET  MULTI_USER 
GO
ALTER DATABASE [FruitBarDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FruitBarDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FruitBarDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FruitBarDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FruitBarDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FruitBarDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [FruitBarDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FruitBarDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [FruitBarDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FruitBarDB]
GO
/****** 物件:  Schema [Fruitbar]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
CREATE SCHEMA [Fruitbar]
GO
/****** 物件:  Table [Fruitbar].[tAlbumArtist]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tAlbumArtist](
	[fId] [int] IDENTITY(1,1) NOT NULL,
	[fAlbumId] [int] NOT NULL,
	[fArtistId] [int] NOT NULL,
	[fCreditRoles] [nvarchar](200) NULL,
 CONSTRAINT [PK_tAlbumArtist] PRIMARY KEY CLUSTERED 
(
	[fId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_tAlbumArtist_fAlbumId_fArtistId] UNIQUE NONCLUSTERED 
(
	[fAlbumId] ASC,
	[fArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tAlbums]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tAlbums](
	[fAlbumId] [int] IDENTITY(1,1) NOT NULL,
	[fAlbumName] [nvarchar](200) NOT NULL,
	[fIsDeleted] [bit] NOT NULL,
	[fReleaseDate] [date] NULL,
	[fCoverPic] [varbinary](max) NULL,
	[fAlbumType] [nvarchar](50) NULL,
 CONSTRAINT [PK_tAlbums] PRIMARY KEY CLUSTERED 
(
	[fAlbumId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tArtists]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tArtists](
	[fArtistId] [int] IDENTITY(1,1) NOT NULL,
	[fArtistName] [nvarchar](200) NOT NULL,
	[fIsDeleted] [bit] NOT NULL,
	[fArtistType] [nvarchar](50) NULL,
 CONSTRAINT [PK_tArtists] PRIMARY KEY CLUSTERED 
(
	[fArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tArtistsSongs]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tArtistsSongs](
	[fId] [int] IDENTITY(1,1) NOT NULL,
	[fSongId] [int] NOT NULL,
	[fArtistId] [int] NOT NULL,
	[fCreditRoles] [nvarchar](200) NULL,
 CONSTRAINT [PK_tArtistsSongs] PRIMARY KEY CLUSTERED 
(
	[fId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_tArtistsSongs_fSongId_fArtistId] UNIQUE NONCLUSTERED 
(
	[fSongId] ASC,
	[fArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tGenre]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tGenre](
	[fGenreId] [int] IDENTITY(1,1) NOT NULL,
	[fGenreName] [nvarchar](50) NOT NULL,
	[fIsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_tGenre] PRIMARY KEY CLUSTERED 
(
	[fGenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_tGenre_fGenreName] UNIQUE NONCLUSTERED 
(
	[fGenreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tSongGenres]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tSongGenres](
	[fId] [int] IDENTITY(1,1) NOT NULL,
	[fSongId] [int] NOT NULL,
	[fGenreId] [int] NOT NULL,
 CONSTRAINT [PK_tSongGenres] PRIMARY KEY CLUSTERED 
(
	[fId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_tSongGenres_fSongId_fGenreId] UNIQUE NONCLUSTERED 
(
	[fSongId] ASC,
	[fGenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tSongs]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tSongs](
	[fSongId] [int] IDENTITY(1,1) NOT NULL,
	[fSongName] [nvarchar](200) NOT NULL,
	[fIsDeleted] [bit] NOT NULL,
	[fLyrics] [nvarchar](max) NULL,
	[fDuration] [int] NULL,
 CONSTRAINT [PK_tSongs] PRIMARY KEY CLUSTERED 
(
	[fSongId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[tSongsAlbums]    指令碼日期: 2026/8/21 上午 11:39:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[tSongsAlbums](
	[fId] [int] IDENTITY(1,1) NOT NULL,
	[fAlbumId] [int] NOT NULL,
	[fSongId] [int] NOT NULL,
	[fTrackNumber] [int] NOT NULL,
 CONSTRAINT [PK_tSongsAlbums] PRIMARY KEY CLUSTERED 
(
	[fId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_tSongsAlbums_fAlbumId_fSongId] UNIQUE NONCLUSTERED 
(
	[fAlbumId] ASC,
	[fSongId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_tSongsAlbums_fAlbumId_fTrackNumber] UNIQUE NONCLUSTERED 
(
	[fAlbumId] ASC,
	[fTrackNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Fruitbar].[tAlbums] ADD  CONSTRAINT [DF_tAlbums_fIsDeleted]  DEFAULT ((0)) FOR [fIsDeleted]
GO
ALTER TABLE [Fruitbar].[tAlbums] ADD  CONSTRAINT [DF_tAlbums_fAlbumType]  DEFAULT (N'Album') FOR [fAlbumType]
GO
ALTER TABLE [Fruitbar].[tArtists] ADD  CONSTRAINT [DF_tArtists_fIsDeleted]  DEFAULT ((0)) FOR [fIsDeleted]
GO
ALTER TABLE [Fruitbar].[tGenre] ADD  CONSTRAINT [DF_tGenre_fIsDeleted]  DEFAULT ((0)) FOR [fIsDeleted]
GO
ALTER TABLE [Fruitbar].[tSongs] ADD  CONSTRAINT [DF_tSongs_fIsDeleted]  DEFAULT ((0)) FOR [fIsDeleted]
GO
ALTER TABLE [Fruitbar].[tAlbumArtist]  WITH CHECK ADD  CONSTRAINT [FK_tAlbumArtist_tAlbums] FOREIGN KEY([fAlbumId])
REFERENCES [Fruitbar].[tAlbums] ([fAlbumId])
GO
ALTER TABLE [Fruitbar].[tAlbumArtist] CHECK CONSTRAINT [FK_tAlbumArtist_tAlbums]
GO
ALTER TABLE [Fruitbar].[tAlbumArtist]  WITH CHECK ADD  CONSTRAINT [FK_tAlbumArtist_tArtists] FOREIGN KEY([fArtistId])
REFERENCES [Fruitbar].[tArtists] ([fArtistId])
GO
ALTER TABLE [Fruitbar].[tAlbumArtist] CHECK CONSTRAINT [FK_tAlbumArtist_tArtists]
GO
ALTER TABLE [Fruitbar].[tArtistsSongs]  WITH CHECK ADD  CONSTRAINT [FK_tArtistsSongs_tArtists] FOREIGN KEY([fArtistId])
REFERENCES [Fruitbar].[tArtists] ([fArtistId])
GO
ALTER TABLE [Fruitbar].[tArtistsSongs] CHECK CONSTRAINT [FK_tArtistsSongs_tArtists]
GO
ALTER TABLE [Fruitbar].[tArtistsSongs]  WITH CHECK ADD  CONSTRAINT [FK_tArtistsSongs_tSongs] FOREIGN KEY([fSongId])
REFERENCES [Fruitbar].[tSongs] ([fSongId])
GO
ALTER TABLE [Fruitbar].[tArtistsSongs] CHECK CONSTRAINT [FK_tArtistsSongs_tSongs]
GO
ALTER TABLE [Fruitbar].[tSongGenres]  WITH CHECK ADD  CONSTRAINT [FK_tSongGenres_tGenre] FOREIGN KEY([fGenreId])
REFERENCES [Fruitbar].[tGenre] ([fGenreId])
GO
ALTER TABLE [Fruitbar].[tSongGenres] CHECK CONSTRAINT [FK_tSongGenres_tGenre]
GO
ALTER TABLE [Fruitbar].[tSongGenres]  WITH CHECK ADD  CONSTRAINT [FK_tSongGenres_tSongs] FOREIGN KEY([fSongId])
REFERENCES [Fruitbar].[tSongs] ([fSongId])
GO
ALTER TABLE [Fruitbar].[tSongGenres] CHECK CONSTRAINT [FK_tSongGenres_tSongs]
GO
ALTER TABLE [Fruitbar].[tSongsAlbums]  WITH CHECK ADD  CONSTRAINT [FK_tSongsAlbums_tAlbums] FOREIGN KEY([fAlbumId])
REFERENCES [Fruitbar].[tAlbums] ([fAlbumId])
GO
ALTER TABLE [Fruitbar].[tSongsAlbums] CHECK CONSTRAINT [FK_tSongsAlbums_tAlbums]
GO
ALTER TABLE [Fruitbar].[tSongsAlbums]  WITH CHECK ADD  CONSTRAINT [FK_tSongsAlbums_tSongs] FOREIGN KEY([fSongId])
REFERENCES [Fruitbar].[tSongs] ([fSongId])
GO
ALTER TABLE [Fruitbar].[tSongsAlbums] CHECK CONSTRAINT [FK_tSongsAlbums_tSongs]
GO
ALTER TABLE [Fruitbar].[tSongsAlbums]  WITH CHECK ADD  CONSTRAINT [CK_tSongsAlbums_fTrackNumber] CHECK  (([fTrackNumber]>(0)))
GO
ALTER TABLE [Fruitbar].[tSongsAlbums] CHECK CONSTRAINT [CK_tSongsAlbums_fTrackNumber]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unit: second' , @level0type=N'SCHEMA',@level0name=N'Fruitbar', @level1type=N'TABLE',@level1name=N'tSongs', @level2type=N'COLUMN',@level2name=N'fDuration'
GO
USE [master]
GO
ALTER DATABASE [FruitBarDB] SET  READ_WRITE 
GO
